micronaut:
  server:
    port: 8082
  application:
    name: crudData
datasources:
  default:
    url: ${JDBC_URL:'jdbc:mysql://localhost:3306/micro_person'}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:'T@l3nt'}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
    db-type: mysql
    schema-generate: none
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
endpoints:
  liquibase:
    enabled: true
    sensitive: false
#vertx:
#  mysql:
#    client:
#      port: 3306
#      host: localhost
#      database: micro_person
#      user: root
#      password: T@l3nt
#      maxSize: 5