micronaut:
  server:
    port: 8082
  application:
    name: selfserviceintegration
microstream:
  storage:
    main:
      root-class: 'com.ssi.integration.IntegrationContainer'
      storage-directory: 'build/integration-storage'