micronaut:
  server:
    port: 8082
  router:
    versioning:
      enabled: true
  application:
    name: micronaut_mysql_hibernate
datasources:
  default:
    url: jdbc:mysql://localhost:3306/ssi
    username: root
    password: pword
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: none
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    reactive: true
    compile-time-hibernate-proxies: true
    entity-scan:
#      classpath: true
      packages:
        - 'com.ssi.integration'
        - 'com.ssi.request'
        -  'com.ssi.result'
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        bytecode:
          provider: none
        show-sql: true
        hbm2ddl:
          auto: update
        connection:
          db-type: mysql
          url: jdbc:mysql://localhost:3306/ssi
          username: root
          password: pword
#    packages-to-scan:
#      - 'com.ssi'
jackson:
  bean-introspection-module: true
  serializationInclusion: NON_NULL

#liquibase:
#  enabled: true
#  datasources:
#    default:
#      change-log: 'classpath:db/liquibase-changelog.xml'
#endpoints:
#  liquibase:
#    enabled: true
#    sensitive: false
