micronaut:
  server:
    port: 8082
  application:
    name: microstream
microstream:
  storage:
    main:
      root-class: 'crud.data.microstream.PersonContainer'
      storage-directory: 'PersonDB/person-storage'