micronaut:
  server:
    port: 8082
  application:
    name: microstream
datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
endpoints:
  liquibase:
    enabled: true
    sensitive: false
microstream:
  storage:
    main:
      root-class: 'crud.data.microstream.PersonContainer'
      storage-directory: 'build/person-storage'