micronaut:
  server:
    port: 8082
  application:
    name: microstream
datasources:
  default:
    url: jdbc:mysql://localhost:3306/micro_person
    username: root
    password: T@l3nt
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: none
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
endpoints:
  liquibase:
    enabled: true
    sensitive: false